const data = [
  {word: "phishing", type: "noun", definition: "A cyberattack using deceptive messages to trick victims into revealing sensitive information."},
  {word: "malware", type: "noun", definition: "Software designed to damage, disrupt, or gain unauthorized access to computer systems."},
  {word: "encrypt", type: "verb", definition: "To convert data into a coded form to prevent unauthorized access."},
  {word: "decrypt", type: "verb", definition: "To convert encrypted data back into its original readable form."},
  {word: "firewall", type: "noun", definition: "A security system that monitors and controls incoming and outgoing network traffic."},
  {word: "authenticate", type: "verb", definition: "To verify the identity of a user, device, or process."},
  {word: "penetration testing", type: "noun", definition: "A simulated cyberattack to test the security of a system or network."},
  {word: "patch", type: "noun", definition: "A software update that fixes vulnerabilities or bugs."},
  {word: "breach", type: "noun", definition: "An incident where unauthorized access to data, applications, or networks occurs."},
  {word: "DDoS", type: "noun", definition: "A distributed denial-of-service attack that overwhelms a target with excessive traffic."},
  {word: "exploit", type: "noun", definition: "A method or code that takes advantage of a vulnerability in a system."},
  {word: "backdoor", type: "noun", definition: "A hidden method of bypassing normal authentication to access a system."},
  {word: "zero-day", type: "noun", definition: "A software vulnerability unknown to the vendor, with no available patch."},
  {word: "sandbox", type: "verb", definition: "To run code in an isolated environment to prevent harm to the system."},
  {word: "hash", type: "verb", definition: "To convert data into a fixed-size string for verification or storage."},
  {word: "keylogger", type: "noun", definition: "Malware that records keystrokes to capture sensitive data."},
  {word: "botnet", type: "noun", definition: "A network of compromised computers controlled by a malicious actor."},
  {word: "social engineering", type: "noun", definition: "Manipulating people into revealing confidential information or performing actions."},
  {word: "brute-force attack", type: "noun", definition: "An attempt to crack a password by trying all possible combinations."},
  {word: "multi-factor authentication", type: "noun", definition: "A security measure requiring multiple verification methods to log in."},
  {word: "intrusion detection system", type: "noun", definition: "A tool that monitors networks or systems for malicious activity."},
  {word: "compromise", type: "verb", definition: "To weaken or expose a system's security to potential threats."},
  {word: "scan", type: "verb", definition: "To analyze a system or network for vulnerabilities or malicious activity."},
  {word: "spoof", type: "verb", definition: "To disguise communication from an unknown source as being from a trusted one."},
  {word: "forensics", type: "noun", definition: "The practice of collecting and analyzing digital evidence from devices or networks."},
  {word: "air-gapped", type: "adjective", definition: "Physically isolated from unsecured networks to prevent cyberattacks."},
  {word: "threat actor", type: "noun", definition: "An individual or group responsible for malicious cyber activities."},
  {word: "log", type: "verb", definition: "To record system events or activities for monitoring and analysis."},
  {word: "exfiltrate", type: "verb", definition: "To steal and transfer data from a system without authorization."},
  {word: "privilege escalation", type: "noun", definition: "The act of gaining higher-level access to systems than originally authorized."}
]

export default data;